# 🎨 Theme
[general]
import = ["~/.config/alacritty/themes/catppuccin-macchiato.toml"]
live_config_reload = true

# 🔤 Font settings
[font]
builtin_box_drawing = true
size = 13.0

[font.normal]
family = "Monaco Nerd Font Mono"
# family = "Cascadia Mono NF"
style = "Regular"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

# ➕ Terminal environment
[env]
TERM = "alacritty"

# 🖱 Mouse behavior
[mouse]
hide_when_typing = true

# 🖋 Cursor style
[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Block"
blinking = "Off"

# 📜 Scrolling
[scrolling]
history = 100000
multiplier = 6

# 🔍 Text selection
[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# 🖥️ Window behavior
[window]
dynamic_title = true
opacity = 1.0
title = "Alacritty"
option_as_alt = "Both"
startup_mode = "Fullscreen"

[window.class]
general = "Alacritty"
instance = "Alacritty"

# 🌈 Color options
[colors]
draw_bold_text_with_bright_colors = true

# 🔗 URL hints
[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
post_processing = true
persist = false
regex = "(https?://[^\"]+)"

# ⌨️ Keybindings
# Disable new tab / close tab
[[keyboard.bindings]]
action = "None"
key = "T"
mods = "Command"
[[keyboard.bindings]]
action = "None"
key = "N"
mods = "Command"
[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"
[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"
# 🐚 Default shell

[terminal.shell]
program = "/opt/homebrew/bin/zsh"
